### PR TITLE
Document the default compute, memory, disk configurations for PCF Metrics

### PR DESCRIPTION
**Pull request by rdy**
Add resource config for 1.3 tile

### CODE REVIEW

**Comment by jncd** [comment]
@rdy Thank you. I'll take a look.

**Comment by jncd** [comment]
@rdy Hello... Questions for you about this PR and it's v1.2 companion: (1) Why doesn't this page appear in the subnav? Have I missed a separate PR for adding it? (2) Also, the page sounds like it is something that a customer should read during the installation/configuration, but I don't see any mention of this in the installing page. When and why does a customer need to refer to this new table? TIA

**Comment by jzlwang** [comment]
@jncd 
(1,2,4) I agree, we can place this table under step 2 of the Resource Config section in [Installing PCF Metrics](http://metrics-review.cfapps.io/pcf-metrics/1-3/installing.html).
(3) This table outlines the default resource config for jobs, which are automatically entered into OpsMan when the tile is installed, and unless the operator expects a high level of use, they are the best fit for the jobs. It's good to have the table in the docs just for reference, or if the operator wants to revert to default values after modifying resource config.

I'll submit another PR for some edits I'd like to make. Thanks :)

**Comment by jncd** [comment]
Thanks @jzlwang Much thanks for making these extra PRs: a worthwhile improvement.

**Pull request merged**
